DROP TABLE IF EXISTS RECIPE CASCADE;
DROP TABLE IF EXISTS INGREDIENT_ALTERNATIVE_NAME CASCADE;
DROP TABLE IF EXISTS INGREDIENT CASCADE;
DROP TABLE IF EXISTS RECIPE_INGREDIENT CASCADE;
DROP TABLE IF EXISTS INVENTORY_ENTRY CASCADE;
DROP TABLE IF EXISTS INVENTORY CASCADE;
DROP TABLE IF EXISTS UNIT CASCADE;
DROP TABLE IF EXISTS KF_USER CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE UNIT
(
    UNIT_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    LABEL VARCHAR(23) UNIQUE NOT NULL,
    PRIMARY KEY (UNIT_ID)
);

CREATE TABLE RECIPE
(
    RECIPE_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    EXTERNAL_ID VARCHAR(32) NULL,
    EXTERNAL_SOURCE VARCHAR(32) NULL,
    EXTERNAL_URL TEXT NULL,
    EXTERNAL_IMG_SRC_URL TEXT NULL,
    NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (RECIPE_ID)
);

CREATE TABLE INGREDIENT
(
    INGREDIENT_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(64) UNIQUE NOT NULL,
    COMMON BOOLEAN NOT NULL,
    PRIMARY KEY (INGREDIENT_ID)
);

CREATE TABLE INGREDIENT_ALTERNATIVE_NAME
(
    INGREDIENT_ALTERNATIVE_NAME_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(64) NOT NULL,
    INGREDIENT_ID UUID NOT NULL,
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT ON DELETE CASCADE,
    PRIMARY KEY (INGREDIENT_ALTERNATIVE_NAME_ID)
);

CREATE TABLE RECIPE_INGREDIENT
(
    RECIPE_INGREDIENT UUID NOT NULL DEFAULT uuid_generate_v4(),
    RECIPE_ID UUID NOT NULL,
    INGREDIENT_ID UUID NOT NULL,
    AMOUNT NUMERIC(9, 3),
    UNIT_ID UUID,
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT ON DELETE RESTRICT,
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE ON DELETE CASCADE,
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT ON DELETE RESTRICT,
    PRIMARY KEY (RECIPE_INGREDIENT),
    unique(RECIPE_ID,INGREDIENT_ID,UNIT_ID)
);

CREATE TABLE INVENTORY
(
    INVENTORY_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    PRIMARY KEY (INVENTORY_ID)
);

CREATE TABLE INVENTORY_ENTRY
(
    INVENTORY_ENTRY_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    INVENTORY_ID UUID NOT NULL,
    INGREDIENT_ID UUID NOT NULL,
    AMOUNT NUMERIC(9, 3) NOT NULL,
    IMAGE_SRC_URL TEXT NULL,
    UNIT_ID UUID NOT NULL,
    FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY ON DELETE CASCADE,
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT ON DELETE CASCADE,
    FOREIGN KEY (UNIT_ID) REFERENCES UNIT ON DELETE RESTRICT,
    PRIMARY KEY (INVENTORY_ENTRY_ID),
    unique (INVENTORY_ID, INGREDIENT_ID,UNIT_ID)
);



CREATE TABLE KF_USER
(
    USER_ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    INVENTORY_ID UUID NOT NULL,
    FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY ON DELETE RESTRICT,
    PRIMARY KEY (USER_ID)
);
