name: Build and publish docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/kuehlfrank/database:latest
      - name: Test run image
        run: docker run -e POSTGRES_PASSWORD=THISISINTERNALONLY --name database -d ghcr.io/kuehlfrank/database:latest
      - name: Wait for 15s
        run: sleep 15s
      - name: Test container still running
        run: if [ "$( docker container inspect -f '{{.State.Status}}' database )" != "running" ]; then exit 1; fi
      - name: Login to ghcr
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Push image to ghcr
        run: docker push ghcr.io/kuehlfrank/database:latest
